# Generated by Django 3.0.3 on 2020-09-04 17:44

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=20)),
                ('password', django_cryptography.fields.encrypt(models.CharField(max_length=20))),
                ('priv', models.IntegerField(choices=[(2, 'User'), (3, 'Operator'), (4, 'Administrator')], default=4)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('ip', models.CharField(blank=True, max_length=45, verbose_name='IP')),
                ('hostname', models.CharField(blank=True, max_length=253)),
                ('port', models.IntegerField(default=623)),
                ('ipC', models.BooleanField(choices=[(True, 'IP'), (False, 'Hostname')], default=True, verbose_name='Connect via IP Address')),
                ('cred', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.Credential')),
            ],
        ),
        migrations.CreateModel(
            name='PowerStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('power_on', models.BooleanField()),
                ('overload', models.BooleanField()),
                ('interlock', models.BooleanField()),
                ('fault', models.BooleanField()),
                ('control_fault', models.BooleanField()),
                ('restore_policy', models.IntegerField()),
                ('last_event', models.CharField(max_length=17)),
                ('intrusion', models.BooleanField()),
                ('front_panel_lockout', models.BooleanField()),
                ('drive_fault', models.BooleanField()),
                ('cooling_fault', models.BooleanField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Host')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
