# Generated by Django 3.0.3 on 2020-09-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerstatus',
            name='timeout',
            field=models.BooleanField(default=False),
        ),
    ]
