# Generated by Django 3.0.3 on 2020-10-10 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_auto_20200915_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('timeout', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Host')),
            ],
        ),
        migrations.CreateModel(
            name='SensorSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('sensor_id', models.IntegerField()),
                ('sensor_name', models.CharField(max_length=255)),
                ('thresholds_unr', models.FloatField(null=True)),
                ('thresholds_ucr', models.FloatField(null=True)),
                ('thresholds_unc', models.FloatField(null=True)),
                ('thresholds_lnc', models.FloatField(null=True)),
                ('thresholds_lcr', models.FloatField(null=True)),
                ('thresholds_lnr', models.FloatField(null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Host')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField()),
                ('raw_value', models.IntegerField(null=True)),
                ('value', models.FloatField(null=True)),
                ('state', models.IntegerField(null=True)),
                ('sensor_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.SensorStatus')),
            ],
        ),
    ]
