# Generated by Django 4.2.4 on 2024-04-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control", "0004_sensorreading_sensorsetting_sensorstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="credential",
            name="password_unencrypted",
            field=models.CharField(default='nothing', max_length=20),
            preserve_default=False,
        ),
    ]
