# Generated by Django 4.2.4 on 2024-04-27 09:15

from django.db import migrations

def forwards_decrypted_char(apps, schema_editor):
    model = apps.get_model("control", "Credential")

    for row in model.objects.all():
        row.password = row.password_encrypted
        row.save(update_fields=["password"])


def reverse_decrypted_char(apps, schema_editor):
    model = apps.get_model("control", "Credential")

    for row in model.objects.all():
        row.password_encrypted = row.password
        row.save(update_fields=["password_encrypted"])



class Migration(migrations.Migration):

    dependencies = [
        ("control", "0007_rename_password_unencrypted_credential_password"),
    ]

    operations = [
        migrations.RunPython(forwards_decrypted_char, reverse_decrypted_char)
    ]
