# Generated by Django 4.2.4 on 2024-04-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("control", "0008_decrypt_passwords"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="credential",
            name="password_encrypted",
        ),
    ]
